### Feature Engineering

In [82]:
import pandas as pd
import numpy as np

In [83]:
df= pd.read_csv("youtube_cleaned_data.csv")

In [84]:
df

,Unnamed: 0,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers
0,5194,9_WBQISVHnw,2307901697,2719637,0,UCK5Q72Uyo73uRPk8PmM2A3w,Genevieve's Playhouse - Learning Videos for Kids,2019-01-05 16:52:49+00:00,623,1,Education,49200000.00
1,2912,CnSylwYOu1E,2178021347,20943413,0,UCgFXm4TI8htWmCyJ6cVPG_A,Toys and Colors,2023-05-05 11:30:04+00:00,30,24,Entertainment,82000000.00
2,3515,hTqtGJwsJVE,1814220195,2853557,0,UCG2CL6EUjG8TVT1Tpl9nJdg,Ms Rachel - Toddler Learning Videos,2022-03-02 17:30:10+00:00,3621,27,Education,18600000.00
3,7091,dNCWe_6HAM8,1184538229,15369289,1116739,UCOmHUn--16B90oW2L6FRR3A,BLACKPINK,2021-09-23 15:00:16+00:00,171,10,Finance,99700000.00
4,6000,GQTUYAhJzY8,1128446716,17865538,44657,UCIH9-O5pX3Qr9bESZB3LYdw,Littos Media,2024-03-20 13:27:10+00:00,15,26,Education,8480000.00
...,...,...,...,...,...,...,...,...,...,...,...,...
7981,5056,Qe_dHjcRarw,1,0,0,UCQWWQGItM_0gON7SpwVE4Vw,Dexa,2026-01-15 14:25:08+00:00,19,22,Technology,6.00
7982,2900,n32p7IvPjJA,1,0,0,UCi897JrsWy7h46W6EQWQDMw,Fit with Suraj,2026-01-22 05:52:58+00:00,13,17,Fitness,155.00
7983,2355,dyqJPxHGj5c,1,0,0,UC4vN_iXfrms4uvDkpQ4rw7Q,Skillvion,2026-01-18 12:45:31+00:00,412,27,Education,89.00
7984,5059,R1KN6mN0gZs,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-09 06:36:28+00:00,142,22,Technology,0.00
7985,5053,WDLQMgGqi0Y,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-12 05:36:11+00:00,56,22,Technology,0.00

In [85]:
df.drop(columns='Unnamed: 0', inplace=True)

In [86]:
df

,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers
0,9_WBQISVHnw,2307901697,2719637,0,UCK5Q72Uyo73uRPk8PmM2A3w,Genevieve's Playhouse - Learning Videos for Kids,2019-01-05 16:52:49+00:00,623,1,Education,49200000.00
1,CnSylwYOu1E,2178021347,20943413,0,UCgFXm4TI8htWmCyJ6cVPG_A,Toys and Colors,2023-05-05 11:30:04+00:00,30,24,Entertainment,82000000.00
2,hTqtGJwsJVE,1814220195,2853557,0,UCG2CL6EUjG8TVT1Tpl9nJdg,Ms Rachel - Toddler Learning Videos,2022-03-02 17:30:10+00:00,3621,27,Education,18600000.00
3,dNCWe_6HAM8,1184538229,15369289,1116739,UCOmHUn--16B90oW2L6FRR3A,BLACKPINK,2021-09-23 15:00:16+00:00,171,10,Finance,99700000.00
4,GQTUYAhJzY8,1128446716,17865538,44657,UCIH9-O5pX3Qr9bESZB3LYdw,Littos Media,2024-03-20 13:27:10+00:00,15,26,Education,8480000.00
...,...,...,...,...,...,...,...,...,...,...,...
7981,Qe_dHjcRarw,1,0,0,UCQWWQGItM_0gON7SpwVE4Vw,Dexa,2026-01-15 14:25:08+00:00,19,22,Technology,6.00
7982,n32p7IvPjJA,1,0,0,UCi897JrsWy7h46W6EQWQDMw,Fit with Suraj,2026-01-22 05:52:58+00:00,13,17,Fitness,155.00
7983,dyqJPxHGj5c,1,0,0,UC4vN_iXfrms4uvDkpQ4rw7Q,Skillvion,2026-01-18 12:45:31+00:00,412,27,Education,89.00
7984,R1KN6mN0gZs,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-09 06:36:28+00:00,142,22,Technology,0.00
7985,WDLQMgGqi0Y,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-12 05:36:11+00:00,56,22,Technology,0.00

In [87]:
# Engagement rate

df['engagement_rate'] = np.where(
    df['views'] > 0,
    ((df['likes'] + df['comments']) / df['views']) * 100,
    0
)

print("\nEngagement Rate: ")
print(df[['video_id', 'views', 'likes','comments', 'engagement_rate']].head())

Engagement Rate:
      video_id       views     likes  comments  engagement_rate
0  9_WBQISVHnw  2307901697   2719637         0             0.12
1  CnSylwYOu1E  2178021347  20943413         0             0.96
2  hTqtGJwsJVE  1814220195   2853557         0             0.16
3  dNCWe_6HAM8  1184538229  15369289   1116739             1.39
4  GQTUYAhJzY8  1128446716  17865538     44657             1.59

In [88]:
# Aggregation based on Genre

genre_stats = df.groupby('genre').agg({
    'views': 'mean',
    'likes': 'mean',
    'comments': 'mean',
    'engagement_rate': 'mean',
    'video_id': 'count'
}).rename(columns={'video_id': 'video_count'})

genre_stats.columns = ['avg_views', 'avg_likes', 'avg_comments', 'avg_engagement', 'video_count']

print("\nGenre-level statistics:")
print(genre_stats)

Genre-level statistics:
                avg_views  avg_likes  avg_comments  avg_engagement  \
genre
Beauty        12153022.08  241491.01       2357.49            2.41
Education     14407084.24  142950.89       1473.50            2.70
Entertainment 44693072.30  532548.25       1729.36            1.58
Finance       10419228.43  201824.77       2819.52            2.94
Fitness        6591048.34  127154.74       1367.07            2.10
Gaming        13418601.17  241623.35      11315.77            1.97
Technology     7489649.15  206698.49       1360.53            2.98
Vlogs          6598437.24  126601.97       1607.16            3.20

               video_count
genre
Beauty                 998
Education              999
Entertainment         1000
Finance                999
Fitness                999
Gaming                1000
Technology             991
Vlogs                 1000

In [89]:
overall_avg_views = df['views'].mean()
overall_avg_engagement = df['engagement_rate'].mean()
total_videos = len(df)

In [90]:
# Saturation Index
# Higher= More saturated
saturation_map = {}
for genre in genre_stats.index:
    video_count = genre_stats.loc[genre, 'video_count']
    avg_views_genre = genre_stats.loc[genre, 'avg_views']
    
    # Avoid division by zero
    if overall_avg_views > 0:
        saturation_map[genre] = video_count / (avg_views_genre / overall_avg_views)
    else:
        saturation_map[genre] = 0

# Map to dataframe
df['saturation_index'] = df['genre'].map(saturation_map)

print("\nSaturation Index:")
print(df.groupby('genre')['saturation_index'].first())

Saturation Index:
genre
Beauty          1189.19
Education       1004.14
Entertainment    324.01
Finance         1388.47
Fitness         2194.91
Gaming          1079.19
Technology      1916.10
Vlogs           2194.64
Name: saturation_index, dtype: float64

In [91]:
df

,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers,engagement_rate,saturation_index
0,9_WBQISVHnw,2307901697,2719637,0,UCK5Q72Uyo73uRPk8PmM2A3w,Genevieve's Playhouse - Learning Videos for Kids,2019-01-05 16:52:49+00:00,623,1,Education,49200000.00,0.12,1004.14
1,CnSylwYOu1E,2178021347,20943413,0,UCgFXm4TI8htWmCyJ6cVPG_A,Toys and Colors,2023-05-05 11:30:04+00:00,30,24,Entertainment,82000000.00,0.96,324.01
2,hTqtGJwsJVE,1814220195,2853557,0,UCG2CL6EUjG8TVT1Tpl9nJdg,Ms Rachel - Toddler Learning Videos,2022-03-02 17:30:10+00:00,3621,27,Education,18600000.00,0.16,1004.14
3,dNCWe_6HAM8,1184538229,15369289,1116739,UCOmHUn--16B90oW2L6FRR3A,BLACKPINK,2021-09-23 15:00:16+00:00,171,10,Finance,99700000.00,1.39,1388.47
4,GQTUYAhJzY8,1128446716,17865538,44657,UCIH9-O5pX3Qr9bESZB3LYdw,Littos Media,2024-03-20 13:27:10+00:00,15,26,Education,8480000.00,1.59,1004.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7981,Qe_dHjcRarw,1,0,0,UCQWWQGItM_0gON7SpwVE4Vw,Dexa,2026-01-15 14:25:08+00:00,19,22,Technology,6.00,0.00,1916.10
7982,n32p7IvPjJA,1,0,0,UCi897JrsWy7h46W6EQWQDMw,Fit with Suraj,2026-01-22 05:52:58+00:00,13,17,Fitness,155.00,0.00,2194.91
7983,dyqJPxHGj5c,1,0,0,UC4vN_iXfrms4uvDkpQ4rw7Q,Skillvion,2026-01-18 12:45:31+00:00,412,27,Education,89.00,0.00,1004.14
7984,R1KN6mN0gZs,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-09 06:36:28+00:00,142,22,Technology,0.00,0.00,1916.10
7985,WDLQMgGqi0Y,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-12 05:36:11+00:00,56,22,Technology,0.00,0.00,1916.10

In [92]:
# Competition Density
# Higher= More Competition

competition_map = {}
for genre in genre_stats.index:
    video_count = genre_stats.loc[genre, 'video_count']
    avg_engagement = genre_stats.loc[genre, 'avg_engagement']
    
    if overall_avg_engagement > 0:
        competition_map[genre] = (video_count / total_videos) * (avg_engagement / overall_avg_engagement)
    else:
        competition_map[genre] = 0

# Map to dataframe
df['competition_density'] = df['genre'].map(competition_map)

print("\nCompetition Density: ")
print(df.groupby('genre')['competition_density'].first())

Competition Density:
genre
Beauty          0.12
Education       0.14
Entertainment   0.08
Finance         0.15
Fitness         0.11
Gaming          0.10
Technology      0.15
Vlogs           0.16
Name: competition_density, dtype: float64

In [93]:
# ROI Potential
# Higher= Better Potential
df['roi_potential'] = np.where(
    df['competition_density'] > 0,
    (df['views'] * df['engagement_rate']) / df['competition_density'],
    0
)

In [94]:
df

,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers,engagement_rate,saturation_index,competition_density,roi_potential
0,9_WBQISVHnw,2307901697,2719637,0,UCK5Q72Uyo73uRPk8PmM2A3w,Genevieve's Playhouse - Learning Videos for Kids,2019-01-05 16:52:49+00:00,623,1,Education,49200000.00,0.12,1004.14,0.14,2003063465.87
1,CnSylwYOu1E,2178021347,20943413,0,UCgFXm4TI8htWmCyJ6cVPG_A,Toys and Colors,2023-05-05 11:30:04+00:00,30,24,Entertainment,82000000.00,0.96,324.01,0.08,26262096768.35
2,hTqtGJwsJVE,1814220195,2853557,0,UCG2CL6EUjG8TVT1Tpl9nJdg,Ms Rachel - Toddler Learning Videos,2022-03-02 17:30:10+00:00,3621,27,Education,18600000.00,0.16,1004.14,0.14,2101698048.12
3,dNCWe_6HAM8,1184538229,15369289,1116739,UCOmHUn--16B90oW2L6FRR3A,BLACKPINK,2021-09-23 15:00:16+00:00,171,10,Finance,99700000.00,1.39,1388.47,0.15,11133702928.38
4,GQTUYAhJzY8,1128446716,17865538,44657,UCIH9-O5pX3Qr9bESZB3LYdw,Littos Media,2024-03-20 13:27:10+00:00,15,26,Education,8480000.00,1.59,1004.14,0.14,13191193262.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7981,Qe_dHjcRarw,1,0,0,UCQWWQGItM_0gON7SpwVE4Vw,Dexa,2026-01-15 14:25:08+00:00,19,22,Technology,6.00,0.00,1916.10,0.15,0.00
7982,n32p7IvPjJA,1,0,0,UCi897JrsWy7h46W6EQWQDMw,Fit with Suraj,2026-01-22 05:52:58+00:00,13,17,Fitness,155.00,0.00,2194.91,0.11,0.00
7983,dyqJPxHGj5c,1,0,0,UC4vN_iXfrms4uvDkpQ4rw7Q,Skillvion,2026-01-18 12:45:31+00:00,412,27,Education,89.00,0.00,1004.14,0.14,0.00
7984,R1KN6mN0gZs,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-09 06:36:28+00:00,142,22,Technology,0.00,0.00,1916.10,0.15,0.00
7985,WDLQMgGqi0Y,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-12 05:36:11+00:00,56,22,Technology,0.00,0.00,1916.10,0.15,0.00

In [95]:
# Rank by ROI Potential for businesses
business_ranking = df.groupby('genre').agg({
    'roi_potential': 'mean',
    'views': 'mean',
    'engagement_rate': 'mean'
}).sort_values('roi_potential', ascending=False)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 10))
business_ranking['roi_potential'] = scaler.fit_transform(business_ranking[['roi_potential']])

print("BEST GENRES FOR BUSINESS MARKETING:")
print(business_ranking)

BEST GENRES FOR BUSINESS MARKETING:
               roi_potential       views  engagement_rate
genre
Entertainment          10.00 44693072.30             1.58
Gaming                  2.97 13418601.17             1.97
Beauty                  2.06 12153022.08             2.41
Technology              1.02  7489649.15             2.98
Finance                 0.99 10419228.43             2.94
Fitness                 0.71  6591048.34             2.10
Education               0.46 14407084.24             2.70
Vlogs                   0.00  6598437.24             3.20

In [96]:
# Barrier to Entry

df['subscriber_barrier'] = df.groupby('genre')['subscribers'].transform('mean')

creator_ranking = df.groupby('genre').agg({
    'roi_potential': 'mean',
    'subscriber_barrier': 'mean',
    'engagement_rate': 'mean',
    'views': 'mean'
})

# Lower barrier = better for new creators
creator_ranking['creator_opportunity'] = (
    creator_ranking['roi_potential'] / (creator_ranking['subscriber_barrier'] / 10000)
)

creator_ranking = creator_ranking.sort_values('creator_opportunity', ascending=False)

print("BEST GENRES FOR NEW CREATORS:")
print(creator_ranking)

BEST GENRES FOR NEW CREATORS:
               roi_potential  subscriber_barrier  engagement_rate       views  \
genre
Fitness         121241757.37          1451992.18             2.10  6591048.34
Beauty          201242947.05          2486493.94             2.41 12153022.08
Entertainment   669960055.57         12415318.82             1.58 44693072.30
Education       106371261.30          2349721.57             2.70 14407084.24
Gaming          254943562.04          7317131.55             1.97 13418601.17
Finance         138204833.59          4319394.49             2.94 10419228.43
Technology      139887669.96          4491977.30             2.98  7489649.15
Vlogs            79493381.92          2971122.19             3.20  6598437.24

               creator_opportunity
genre
Fitness                  835002.83
Beauty                   809344.21
Entertainment            539623.72
Education                452697.30
Gaming                   348420.09
Finance                  319963.44
Technology               311416.69
Vlogs                    267553.39

In [97]:
# Growth Rate

if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'])
    
    # Calculate videos per month by genre
    df['year_and_month'] = df['date'].dt.to_period('M')
    
    monthly_counts = df.groupby(['genre', 'year_and_month']).size().reset_index(name='monthly_video_count')
    
    # Calculate growth rate (percentage change month over month)
    monthly_counts['growth_rate'] = monthly_counts.groupby('genre')['monthly_video_count'].pct_change() * 100
    
    # Get the latest growth rate for each genre
    latest_growth = monthly_counts.groupby('genre').tail(1)[['genre', 'growth_rate']]
    latest_growth = latest_growth.set_index('genre')['growth_rate'].to_dict()
    
    # Map to main dataframe
    df['growth_rate'] = df['genre'].map(latest_growth).fillna(0)
    
    print("\nGrowth Rate: ")
    print(df.groupby('genre')['growth_rate'].first())
else:
    print("\nNo 'date' column found - skipping Growth Rate calculation")
    df['growth_rate'] = 0

Growth Rate:
genre
Beauty           511.54
Education        488.24
Entertainment    596.67
Finance          473.33
Fitness         1500.00
Gaming           861.90
Technology       371.70
Vlogs            475.38
Name: growth_rate, dtype: float64

C:\Users\aarushi\AppData\Local\Temp\ipykernel_130816\695691433.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df['year_and_month'] = df['date'].dt.to_period('M')

In [98]:
df

,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers,engagement_rate,saturation_index,competition_density,roi_potential,subscriber_barrier,year_and_month,growth_rate
0,9_WBQISVHnw,2307901697,2719637,0,UCK5Q72Uyo73uRPk8PmM2A3w,Genevieve's Playhouse - Learning Videos for Kids,2019-01-05 16:52:49+00:00,623,1,Education,49200000.00,0.12,1004.14,0.14,2003063465.87,2349721.57,2019-01,488.24
1,CnSylwYOu1E,2178021347,20943413,0,UCgFXm4TI8htWmCyJ6cVPG_A,Toys and Colors,2023-05-05 11:30:04+00:00,30,24,Entertainment,82000000.00,0.96,324.01,0.08,26262096768.35,12415318.82,2023-05,596.67
2,hTqtGJwsJVE,1814220195,2853557,0,UCG2CL6EUjG8TVT1Tpl9nJdg,Ms Rachel - Toddler Learning Videos,2022-03-02 17:30:10+00:00,3621,27,Education,18600000.00,0.16,1004.14,0.14,2101698048.12,2349721.57,2022-03,488.24
3,dNCWe_6HAM8,1184538229,15369289,1116739,UCOmHUn--16B90oW2L6FRR3A,BLACKPINK,2021-09-23 15:00:16+00:00,171,10,Finance,99700000.00,1.39,1388.47,0.15,11133702928.38,4319394.49,2021-09,473.33
4,GQTUYAhJzY8,1128446716,17865538,44657,UCIH9-O5pX3Qr9bESZB3LYdw,Littos Media,2024-03-20 13:27:10+00:00,15,26,Education,8480000.00,1.59,1004.14,0.14,13191193262.62,2349721.57,2024-03,488.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7981,Qe_dHjcRarw,1,0,0,UCQWWQGItM_0gON7SpwVE4Vw,Dexa,2026-01-15 14:25:08+00:00,19,22,Technology,6.00,0.00,1916.10,0.15,0.00,4491977.30,2026-01,371.70
7982,n32p7IvPjJA,1,0,0,UCi897JrsWy7h46W6EQWQDMw,Fit with Suraj,2026-01-22 05:52:58+00:00,13,17,Fitness,155.00,0.00,2194.91,0.11,0.00,1451992.18,2026-01,1500.00
7983,dyqJPxHGj5c,1,0,0,UC4vN_iXfrms4uvDkpQ4rw7Q,Skillvion,2026-01-18 12:45:31+00:00,412,27,Education,89.00,0.00,1004.14,0.14,0.00,2349721.57,2026-01,488.24
7984,R1KN6mN0gZs,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-09 06:36:28+00:00,142,22,Technology,0.00,0.00,1916.10,0.15,0.00,4491977.30,2026-01,371.70
7985,WDLQMgGqi0Y,1,0,0,UC3VZb2ti0GDQCh9tk7agrRQ,TechyHub,2026-01-12 05:36:11+00:00,56,22,Technology,0.00,0.00,1916.10,0.15,0.00,4491977.30,2026-01,371.70

In [99]:
# Calculates genre-level metrics

genre_metrics = df.groupby('genre').agg({
    'engagement_rate': 'mean',
    'saturation_index': 'first',
    'competition_density': 'first',
    'roi_potential': 'mean',
    'views': 'mean',
    'subscribers': 'mean',
    'video_id': 'count'
}).round(2)

genre_metrics.columns = ['avg_engagement_rate', 'saturation_index', 
                          'competition_density', 'avg_roi_potential',
                          'avg_views', 'avg_subscribers', 'video_count']

# Calculates barrier for new creators (subscriber barrier)
genre_metrics['creator_barrier'] = genre_metrics['avg_subscribers']

# Calculates business score (high ROI + high views)
genre_metrics['business_score'] = (
    (genre_metrics['avg_roi_potential'] / genre_metrics['avg_roi_potential'].max() * 50) +
    (genre_metrics['avg_views'] / genre_metrics['avg_views'].max() * 30) +
    (genre_metrics['avg_engagement_rate'] / genre_metrics['avg_engagement_rate'].max() * 20)
)

# Calculates creator score (high ROI + low barrier)
genre_metrics['creator_score'] = (
    (genre_metrics['avg_roi_potential'] / genre_metrics['avg_roi_potential'].max() * 40) +
    ((1 / genre_metrics['creator_barrier']) * 1000000 * 40) +
    (genre_metrics['avg_engagement_rate'] / genre_metrics['avg_engagement_rate'].max() * 20)
)


print(genre_metrics)

               avg_engagement_rate  saturation_index  competition_density  \
genre
Beauty                        2.41           1189.19                 0.12
Education                     2.70           1004.14                 0.14
Entertainment                 1.58            324.01                 0.08
Finance                       2.94           1388.47                 0.15
Fitness                       2.10           2194.91                 0.11
Gaming                        1.97           1079.19                 0.10
Technology                    2.98           1916.10                 0.15
Vlogs                         3.20           2194.64                 0.16

               avg_roi_potential   avg_views  avg_subscribers  video_count  \
genre
Beauty              201242947.05 12153022.08       2486493.94          998
Education           106371261.30 14407084.24       2349721.57          999
Entertainment       669960055.57 44693072.30      12415318.82         1000
Finance             138204833.59 10419228.43       4319394.49          999
Fitness             121241757.37  6591048.34       1451992.18          999
Gaming              254943562.04 13418601.17       7317131.56         1000
Technology          139887669.96  7489649.15       4491977.30          991
Vlogs                79493381.92  6598437.24       2971122.19         1000

               creator_barrier  business_score  creator_score
genre
Beauty              2486493.94           38.24          43.16
Education           2349721.57           34.48          40.25
Entertainment      12415318.82           89.88          53.10
Finance             4319394.49           35.68          35.89
Fitness             1451992.18           26.60          47.91
Gaming              7317131.56           40.35          33.00
Technology          4491977.30           34.09          35.88
Vlogs               2971122.19           30.36          38.21

In [100]:
genre_potential = df.groupby('genre').agg({
    'roi_potential': 'mean',
    'views': 'mean',
    'engagement_rate': 'mean',
    'competition_density': 'mean',
    'saturation_index': 'first',
    'video_id': 'count'
}).round(2)

genre_potential.columns = ['avg_roi_potential', 'avg_views', 'avg_engagement', 
                           'competition', 'saturation', 'video_count']

# Sort by ROI potential
genre_potential = genre_potential.sort_values('avg_roi_potential', ascending=False)

print(" Genres based on ROI POTENTIAL")

print(genre_potential)

 Genres based on ROI POTENTIAL
               avg_roi_potential   avg_views  avg_engagement  competition  \
genre
Entertainment       669960055.57 44693072.30            1.58         0.08
Gaming              254943562.04 13418601.17            1.97         0.10
Beauty              201242947.05 12153022.08            2.41         0.12
Technology          139887669.96  7489649.15            2.98         0.15
Finance             138204833.59 10419228.43            2.94         0.15
Fitness             121241757.37  6591048.34            2.10         0.11
Education           106371261.30 14407084.24            2.70         0.14
Vlogs                79493381.92  6598437.24            3.20         0.16

               saturation  video_count
genre
Entertainment      324.01         1000
Gaming            1079.19         1000
Beauty            1189.19          998
Technology        1916.10          991
Finance           1388.47          999
Fitness           2194.91          999
Education         1004.14          999
Vlogs             2194.64         1000

In [102]:
df.to_csv("youtube_data.csv")

In [103]:
genre_metrics.to_csv("youtube_genres.csv")