In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [22]:
df=pd.read_csv('youtube_data.csv')

In [23]:
df.head()

,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,49p7hMbCpys,61074032,2948352,4611,UCglXlpWjIi95auM3umWWLdw,Tech Master Shorts,2023-05-04 08:03:00+00:00,56,28,Technology,26500000.0,NaN,NaN,NaN
1,ofzwCrlxywc,59182092,1955798,1576,UCoL68NLLSUQqEDwMZPvrdEg,TechBurner Shorts,2023-09-01 17:13:48+00:00,35,28,Technology,6390000.0,NaN,NaN,NaN
2,IZl5ipoTIEA,53162940,2647209,3112,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,2023-03-14 10:14:49+00:00,60,28,Technology,22200000.0,NaN,NaN,NaN
3,FNnK1J-BdiM,43007923,1908958,7863,UCBJycsmduvYEL83R_U4JriQ,Marques Brownlee,2023-06-22 04:03:29+00:00,56,28,Technology,20700000.0,NaN,NaN,NaN
4,vkBQW8NZk9k,39995391,1962796,5058,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,2023-05-14 13:01:39+00:00,60,28,Technology,22200000.0,NaN,NaN,NaN

In [24]:
cols_to_drop = ['Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
df.drop(columns=cols_to_drop, inplace=True)

df.head()

,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers
0,49p7hMbCpys,61074032,2948352,4611,UCglXlpWjIi95auM3umWWLdw,Tech Master Shorts,2023-05-04 08:03:00+00:00,56,28,Technology,26500000.0
1,ofzwCrlxywc,59182092,1955798,1576,UCoL68NLLSUQqEDwMZPvrdEg,TechBurner Shorts,2023-09-01 17:13:48+00:00,35,28,Technology,6390000.0
2,IZl5ipoTIEA,53162940,2647209,3112,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,2023-03-14 10:14:49+00:00,60,28,Technology,22200000.0
3,FNnK1J-BdiM,43007923,1908958,7863,UCBJycsmduvYEL83R_U4JriQ,Marques Brownlee,2023-06-22 04:03:29+00:00,56,28,Technology,20700000.0
4,vkBQW8NZk9k,39995391,1962796,5058,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,2023-05-14 13:01:39+00:00,60,28,Technology,22200000.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   video_id      8000 non-null   object
 1   views         8000 non-null   int64
 2   likes         8000 non-null   int64
 3   comments      8000 non-null   int64
 4   channel_id    8000 non-null   object
 5   channel_name  8000 non-null   object
 6   date          8000 non-null   object
 7   duration      8000 non-null   int64
 8   category_id   8000 non-null   int64
 9   genre         8000 non-null   object
 10  subscribers   7997 non-null   float64
dtypes: float64(1), int64(5), object(5)
memory usage: 687.6+ KB

In [26]:
df['subscribers'].isnull().sum()

np.int64(3)

In [27]:
print("total rows:", len(df))

dup=df[df.duplicated(subset="video_id",keep=False)]
print("No. of duplicate rows", dup.shape[0])
print(dup.sort_values("video_id"))

total rows: 8000
No. of duplicate rows 7
     video_id    views   likes  comments                channel_id  \
99     #NAME?  5710236  173715       500  UC7ySZBzw3bqY7MTk6irMd0Q
7606   #NAME?  4710156  117082      4770  UCMiJRAwDNSNzuYeN2uWa0pA
7755   #NAME?   148604    5741       220  UCCiGY0qGJ6ArOh8FpwgmxJQ
7795   #NAME?   108803     504        40  UCUq3Rn72jfQ-86CaCxj7XzA
7862   #NAME?    29897       0         2  UCAnUCptKa5btEzfpaepOpLw
7939   #NAME?  2227984  165932      1107  UCFar6t6OF-q2Y6rBuoDhpOg
7986   #NAME?  5615167   34686       772  UCOKWRzGE08ESvQ5JwxiwWKQ

              channel_name                       date  duration  category_id  \
99    SimpleGhar Malayalam  2023-09-09 12:30:00+00:00        36           28
7606        Mrwhosetheboss  2025-12-22 12:18:02+00:00      1653           28
7755                  ryan  2026-01-19 20:29:22+00:00        70           22
7795          Created Tech  2026-01-10 08:58:47+00:00      1235           28
7862       Ayansh Thailiya  2026-01-20 13:38:00+00:00       126           27
7939           Massy Arias  2024-06-11 18:20:16+00:00        51           26
7986  Telugu Music Station  2025-06-23 15:30:00+00:00       336           10

           genre  subscribers
99    Technology    2300000.0
7606  Technology   22200000.0
7755  Technology      38800.0
7795  Technology     285000.0
7862  Technology      13100.0
7939     Fitness    1410000.0
7986      Beauty      34400.0

In [28]:
duplicate_counts = df["video_id"].value_counts()
print(duplicate_counts[duplicate_counts > 1])

df.head()

video_id
#NAME?    7
Name: count, dtype: int64

,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers
0,49p7hMbCpys,61074032,2948352,4611,UCglXlpWjIi95auM3umWWLdw,Tech Master Shorts,2023-05-04 08:03:00+00:00,56,28,Technology,26500000.0
1,ofzwCrlxywc,59182092,1955798,1576,UCoL68NLLSUQqEDwMZPvrdEg,TechBurner Shorts,2023-09-01 17:13:48+00:00,35,28,Technology,6390000.0
2,IZl5ipoTIEA,53162940,2647209,3112,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,2023-03-14 10:14:49+00:00,60,28,Technology,22200000.0
3,FNnK1J-BdiM,43007923,1908958,7863,UCBJycsmduvYEL83R_U4JriQ,Marques Brownlee,2023-06-22 04:03:29+00:00,56,28,Technology,20700000.0
4,vkBQW8NZk9k,39995391,1962796,5058,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,2023-05-14 13:01:39+00:00,60,28,Technology,22200000.0

In [29]:
df= df.sort_values("views", ascending=False).drop_duplicates(subset="video_id", keep="first")

df

,video_id,views,likes,comments,channel_id,channel_name,date,duration,category_id,genre,subscribers
5194,9_WBQISVHnw,2307901697,2719637,0,UCK5Q72Uyo73uRPk8PmM2A3w,Genevieve's Playhouse - Learning Videos for Kids,2019-01-05 16:52:49+00:00,623,1,Education,49200000.0
2912,CnSylwYOu1E,2178021347,20943413,0,UCgFXm4TI8htWmCyJ6cVPG_A,Toys and Colors,2023-05-05 11:30:04+00:00,30,24,Entertainment,82000000.0
3515,hTqtGJwsJVE,1814220195,2853557,0,UCG2CL6EUjG8TVT1Tpl9nJdg,Ms Rachel - Toddler Learning Videos,2022-03-02 17:30:10+00:00,3621,27,Education,18600000.0
7091,dNCWe_6HAM8,1184538229,15369289,1116739,UCOmHUn--16B90oW2L6FRR3A,BLACKPINK,2021-09-23 15:00:16+00:00,171,10,Finance,99700000.0
6000,GQTUYAhJzY8,1128446716,17865538,44657,UCIH9-O5pX3Qr9bESZB3LYdw,Littos Media,2024-03-20 13:27:10+00:00,15,26,Education,8480000.0
...,...,...,...,...,...,...,...,...,...,...,...
5062,Es4R2-hwPfA,0,0,0,UCeRrDeyGfcouZjkvLLSnFlQ,Tech Fun,2026-01-20 22:30:00+00:00,49,28,Technology,3820.0
5705,WwLuqZUKrHw,0,0,0,UCUCLzOUfgoWnDgi5gzQyFdA,Michelle Hardin,2026-01-22 00:47:17+00:00,61,22,Beauty,0.0
7553,hdDjWRoLyJo,0,59,6,UCg7OZFriVCc1YI6JrVoK2eg,YouTube Movies,2023-11-29 18:32:03+00:00,6301,30,Finance,0.0
2354,Atw5Dykqoz0,0,0,0,UCW7DWw4F3vgbIqpiK-N1wDg,Which Wins? – Software Comparisons & Tutorials,2026-01-20 16:56:46+00:00,164,27,Education,442.0
1748,9EljnTz4lFk,0,0,0,UCMI_1KRVacgteBmRRogH1Rw,TechTGShorts,2026-01-22 03:30:19+00:00,42,28,Technology,0.0

In [14]:
df = df[df['video_id'] != '#NAME?']

df

,video_id,views,likes,comments,channel_id,channel_name,published_date,duration,category_id,genre,subscribers
5194,9_WBQISVHnw,2307901697,2719637,0,UCK5Q72Uyo73uRPk8PmM2A3w,Genevieve's Playhouse - Learning Videos for Kids,2019-01-05 16:52:49+00:00,623,1,Education,49200000.0
2912,CnSylwYOu1E,2178021347,20943413,0,UCgFXm4TI8htWmCyJ6cVPG_A,Toys and Colors,2023-05-05 11:30:04+00:00,30,24,Entertainment,82000000.0
3515,hTqtGJwsJVE,1814220195,2853557,0,UCG2CL6EUjG8TVT1Tpl9nJdg,Ms Rachel - Toddler Learning Videos,2022-03-02 17:30:10+00:00,3621,27,Education,18600000.0
7091,dNCWe_6HAM8,1184538229,15369289,1116739,UCOmHUn--16B90oW2L6FRR3A,BLACKPINK,2021-09-23 15:00:16+00:00,171,10,Finance,99700000.0
6000,GQTUYAhJzY8,1128446716,17865538,44657,UCIH9-O5pX3Qr9bESZB3LYdw,Littos Media,2024-03-20 13:27:10+00:00,15,26,Education,8480000.0
...,...,...,...,...,...,...,...,...,...,...,...
2354,Atw5Dykqoz0,0,0,0,UCW7DWw4F3vgbIqpiK-N1wDg,Which Wins? – Software Comparisons & Tutorials,2026-01-20 16:56:46+00:00,164,27,Education,442.0
5062,Es4R2-hwPfA,0,0,0,UCeRrDeyGfcouZjkvLLSnFlQ,Tech Fun,2026-01-20 22:30:00+00:00,49,28,Technology,3820.0
1748,9EljnTz4lFk,0,0,0,UCMI_1KRVacgteBmRRogH1Rw,TechTGShorts,2026-01-22 03:30:19+00:00,42,28,Technology,0.0
5705,WwLuqZUKrHw,0,0,0,UCUCLzOUfgoWnDgi5gzQyFdA,Michelle Hardin,2026-01-22 00:47:17+00:00,61,22,Beauty,0.0
7553,hdDjWRoLyJo,0,59,6,UCg7OZFriVCc1YI6JrVoK2eg,YouTube Movies,2023-11-29 18:32:03+00:00,6301,30,Finance,0.0

In [30]:
df["video_id"].value_counts().max()

1

In [31]:
df["date"] = pd.to_datetime(df["date"])

In [32]:
df = df[df["views"] > 0]
df = df[df["likes"] <= df["views"]]
df = df[df["comments"] <= df["views"]]

In [33]:
df = df[df["date"] >= "2018-01-01"]

In [34]:
print(f"Loaded {len(df)} records with {len(df.columns)} columns")
print(f"Columns: {df.columns.tolist()}\n")

Loaded 7986 records with 11 columns
Columns: ['video_id', 'views', 'likes', 'comments', 'channel_id', 'channel_name', 'date', 'duration', 'category_id', 'genre', 'subscribers']

In [40]:
df.isna().sum()

video_id        0
views           0
likes           0
comments        0
channel_id      0
channel_name    0
date            0
duration        0
category_id     0
genre           0
subscribers     3
dtype: int64

In [39]:
df.duplicated().any()

np.False_

In [41]:
df.to_csv('youtube_cleaned_date.csv')